// app/layout.tsx - Server Component
import type { Metadata } from "next";
import { Geist, Geist_Mono, Playwrite_GB_J, Coiny } from "next/font/google";
import "./globals.css";
import ClientLayout from "@/components/layout/client-layout";

// ... font definitions ...

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`... fonts ...`}>
      <body className="min-h-full flex flex-col">
        <ClientLayout>{children}</ClientLayout> {/* ← ONLY this */}
      </body>
    </html>
  );
}
